namespace: ""
appName: "ocr-service"
replicaCount: 1
image:
  repository: "ghcr.io/nexaflowb2b/ocr-service"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: "ocr-service"
  port: 8007
config:
  map: {}
secret:
  create: true
  sealedData:
    DATABASE_URL: "" # Paste your kubeseal output here
    SECRET_KEY: "" # Paste your kubeseal output here
env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: ocr-service-secret
        key: SECRET_KEY
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: ocr-service-secret
        key: DATABASE_URL
  - name: ALGORITHM
    value: "HS256"
dbInit:
  enabled: false
  command:
    - python
    - initdb.py
  backoffLimit: 6
  activeDeadlineSeconds: 600


