apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexaflow-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: argocd/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
