namespace: ""
appName: "analytics-service"
replicaCount: 1
image:
  repository: "ghcr.io/nexaflowb2b/analytics-service"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: "analytics-service"
  port: 8006
config:
  map: {}
secret:
  create: true
  sealedData:
    SECRET_KEY: "" # Paste your kubeseal output here
env: []


imagePullSecrets:
  - name: ghcr-login
