apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexaflow.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secret.sealedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}