namespace: "dev"
secret:
  create: true
  sealedData:
    DATABASE_URL: "AgC+xpcXvREkuUb3HBTPPi+kmYNwLpfrKqRuk6QF0tD9bXIkmsHM1UU49uFSqmNGsT1NzkJ4VrOFnyih3FTJthm/Q2CKSgA3WoqhNTp9sKntLX8jHZkIhr60VqTdQZNaN7kMUPiFJpvGX7x+wzCdGeeHFG1f8upPGSiGk8q3MwxqASMkIILfitVl8Ud9LPnLQM8GMb6JaVD6s7GJO8GaiGMstUIznuVgnuFckuAlqP7Mm2gIFQ0i0SjqMzhqkZIbtrK7XAODjblyzZtXou8lPtJfi24XMbCQTPmQwqn+sK9/RqWk4Nr7a73IdhepxW24XevInJ8X9D0Awt/IHFLtF3QSz8pPsUmZECXLG2M5BfK/lfRbXiey1uWMGHB4naBqfrneZ0pUGDAhu7O9TElYOwYj0mNpf+2IMunKhRoEdIapOuL3/VS/rHTYo4KVMctqWr2WgqP6uZ6GZCjxTd3h7rfaA2UPfWJlITwSRRl62QO7BV82wmNwaX6dIeF5OYa0D14QO3ZLxZ1G5y0MbSeer3waAqdVTBGTedfnK1SPeB59a7JP6H4je8gBxy59soDBqk16qeXsq68jrBScN4QZXlVnWzPiDtRPcP4NoHHt8cpxJh5QdGZGEfyKyjWQc6R1CAFbV/5wH7f5tEFbuA+JwGuvByOMyqy/aWXcQyhKObiYdOFgPvIeCaEXEJ9n1ZqcS4dxFCthCwg9osjG8SH6x/eCCbjTCxIeKl0//AQG9u2hnkmSiOoNCkrI5sBt5IwC62XZoASAiFwuv0xypJ9fiQ+5nt6YbQ=="
    SECRET_KEY: "AgCaKmM23e4Jlbrn0+PDGxDJnA1MiaoYJvxydEksVQwQnTggZiaBe5p+PSVf+wzCwmNw4W32OSLvjSp8phuwvQ+iIVYX53KBXOpW38Cy8CyRnEjbwZWiGZIPrEW4mAlEt302/oFC/soyIMlfF77KgvsQ0nPHg9SRxervvNshR+O8w5KdYhu4THhJvq/uo1Gm6wNJqMdF8xD8G2UPUReyNsWbDMX9s1Tm9jhXiWScd/iP0/bP7K3g9HW7+nPxdWE6zujMohUrYugxSB29EpDthrO7ppYz8sJ/W2EkG9gj0xT5IcK6suV8E3/uxpuhs+VfwjnZV75FvKuGoA25VePnCRMzZGYPzDbNCGQ+7a8UdqWq9+AAYjNFrBSibENVBygrinC+iLqOYKxLiAXC+5nqE3p8saRjxMOsGS6r/NlYgr1G4/jlImwNGjgj2u9kV9auKatxJH8yIyV0uwyp+Q9htl0LXXOTT7OoLWgNmDSm6YO0WBCl3IFu2tBRpTceMh+OFeQ/gGK93zcAzU50IUs81VW2Fr6pkobBpmmIBDxnPdIWHHFyGiP6Sp9o5cHb4NHK3Ag1XVOk5zQ9rLe4c1YQKSoYlzJ5IlP+ky0AP10U3ZBgiTcFqVkKs2tuDPXIn1HWDE2u9N5VVkEzoo5x7/z5SZzxr/omQNzqEe8XR6+CR6PH4ShbkDrehbilG5FxTOxVAIuHGu82/vzAHbxc2klImCR9T1yjYjuapNtOO43ZjnVJLA=="
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: auth-service-secret
        key: DATABASE_URL
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: auth-service-secret
        key: SECRET_KEY
  - name: ALGORITHM
    value: "HS256"
  - name: ACCESS_TOKEN_EXPIRE_MINUTES
    value: "60"
image:
  tag: e267a
