namespace: "dev"
secret:
  create: true
  sealedData:
    DATABASE_URL: "AgCysndEA0u2lGLx6ZlyhLcHbdBH2B3A2v/L4Mb73+6sBszG4LjYFYasMJak8mSjAHX6olUt33sh2ZR+YgGEu3dF7lHGO+SXq5QfrW6fVAkliqCqvLQbIoQbl0QC5HhEgAs47jgR2Qt1CE4RYXjlTOXH4DV0v9FgVmw1sre5q6N4r4tsmjw/LZuAWvmWJNCipYwPozNzIxcnSa+vu/1H+OTdE0oPsLjnvQpWA5Zfy6cOpoDN07aVLjRfVE+88RvPv8mpuaJXT4PVRpn9yjreTjlkAD2VwaWclCJXkn8irqfIWbQoC5hZoLc7E47zL1+fRIwEvEPRbbKG4Ygqp1JeBJLUvFB+NeVeXxwctB2LOJPTAGlkIj46eKMNKiN/yu4eJJbh3tVJsrjeiPjYrFm8Z+my0rdCZhCZADx+a4pFvVeOSD1O2fPrZD9HL49wriEYcGxO4LJfdMYYFMmqA88DkJih0W3MxEGL1Kc+XU2cgP+iyMQbjdhX30zVHh+8f1h4RfaTbrBktOTwTN3e/S6jkX2MIAymmMoZDW/AaROHaW/RGaYyG5IjYIVEkw+YCSNmSJIL4VgNkOc36Na96iviEwJ/5t1u8DdDSF3aQyrjl+b2HpO3NkiXEvET2dhi9I1BCko5njhKJaVTIIPtVegAfOyJ+3WtwQEMxfUGai+J3sUnSybJE9DnJWyt4ffDc+9BvjH99cmeSqf0pC33gyyt4FwVNxYtCNmPin82TF1QOtI7qSJLRX3KtpJJwJ1aJ1S+77hQm9SWl1mi5mNX"
    SECRET_KEY: "AgAwXyPKgAZnNzh85tyjThNUh1AZmhFZ0Aqwndvp5d8kklHWzC00Rk3PNNskmEBTNfVhXq/GGRBnYOrHvK28+T4L5EtoZZ0T8/QC1zP3Mq7EddplZpodGvIDyF6xxtXjD3Ynw2a+hGn2RitKIloWA3L/8JT7u9DmS7+efH0AxizZfBzxIGlTopC1gUeSnVRmHivR+VpGKfkcRZ8FETe2cOUSrsL3h6oiTST+S9p1vqiNDD6zlCUtWdNsm5a6D+ZC3G8rVFNstF6Muj0cl9gG3I0a1GdCSOdOsKmmmpinT8AddGdxjNnFLk5GkZWMl7Kf66pxT4tz1H6tiSs9+sl9EG1WmGlJC54m9+Li5HOxWB7jKSUh5+bKGD1VZkbJz917lAKrBDJDT3m6XZONgAlM91QhJEiReCFFE91ixgkDUHJau6lQHkdm+SA+s9TrEgsRzRvfKey/7JvroBGMZACw5Ik3Jm+a5VA0QZSSshblAR2Ed++30TZzd/DxrCXHXd5skvJG7hXeMRzQ6a9eM3sPzdgjGbGhUuntuFla1fFK8MHRqk29E5N9eZnUWI85vvqAFicsi74MDHs0pNFFB4V3bhKBXsLxaOB1522dQkRhZT7vf+ZYqc30yEN1nPkQ8z1AYQQH00PvebBdxMd4FZsNurq9HB88KDDGjeyr/jO5IIpisIEhWpyu6Ijgl1TaI2+vJPo9rIE0xH1xv/+xas0c/87AhqugAzqtWnPmx880P3rzHw=="
env:
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres@postgres:5432/finventory_db"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: auth-service-secret
        key: SECRET_KEY
  - name: ALGORITHM
    value: "HS256"
  - name: ACCESS_TOKEN_EXPIRE_MINUTES
    value: "60"
image:
  tag: e267a
