{{- if .Values.dbInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-initdb
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: {{ .Values.dbInit.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.dbInit.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-initdb
    spec:
      restartPolicy: OnFailure
      containers:
        - name: initdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.dbInit.command | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
{{- end }}

