{{- if and .Values.secret.create .Values.secret.sealedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "nexaflow.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secret.sealedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
