{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
