apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: "AgC+xpcXvREkuUb3HBTPPi+kmYNwLpfrKqRuk6QF0tD9bXIkmsHM1UU49uFSqmNGsT1NzkJ4VrOFnyih3FTJthm/Q2CKSgA3WoqhNTp9sKntLX8jHZkIhr60VqTdQZNaN7kMUPiFJpvGX7x+wzCdGeeHFG1f8upPGSiGk8q3MwxqASMkIILfitVl8Ud9LPnLQM8GMb6JaVD6s7GJO8GaiGMstUIznuVgnuFckuAlqP7Mm2gIFQ0i0SjqMzhqkZIbtrK7XAODjblyzZtXou8lPtJfi24XMbCQTPmQwqn+sK9/RqWk4Nr7a73IdhepxW24XevInJ8X9D0Awt/IHFLtF3QSz8pPsUmZECXLG2M5BfK/lfRbXiey1uWMGHB4naBqfrneZ0pUGDAhu7O9TElYOwYj0mNpf+2IMunKhRoEdIapOuL3/VS/rHTYo4KVMctqWr2WgqP6uZ6GZCjxTd3h7rfaA2UPfWJlITwSRRl62QO7BV82wmNwaX6dIeF5OYa0D14QO3ZLxZ1G5y0MbSeer3waAqdVTBGTedfnK1SPeB59a7JP6H4je8gBxy59soDBqk16qeXsq68jrBScN4QZXlVnWzPiDtRPcP4NoHHt8cpxJh5QdGZGEfyKyjWQc6R1CAFbV/5wH7f5tEFbuA+JwGuvByOMyqy/aWXcQyhKObiYdOFgPvIeCaEXEJ9n1ZqcS4dxFCthCwg9osjG8SH6x/eCCbjTCxIeKl0//AQG9u2hnkmSiOoNCkrI5sBt5IwC62XZoASAiFwuv0xypJ9fiQ+5nt6YbQ=="
