apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: nexaflow_password
  POSTGRES_DB: finventory_db
  DATABASE_URL: postgresql://postgres:nexaflow_password@postgres:5432/finventory_db
