apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: frontend-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: auth-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/auth-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: inventory-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/inventory-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: finance-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/finance-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: invoice-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/invoice-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ai-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/ai-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: analytics-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/analytics-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ocr-service-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/NexaflowB2B/nexaflow-helm.git
    path: Charts/ocr-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
---

