namespace: ""
appName: "ocr-service"
replicaCount: 1
image:
  repository: "ghcr.io/nexaflowb2b/ocr-service"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: "ocr-service"
  port: 8007
config:
  map: {}
secret:
  create: true
  sealedData:
    SECRET_KEY: "" # Paste your kubeseal output here
env: []


imagePullSecrets:
  - name: ghcr-login
