namespace: ""
appName: "finance-service"
replicaCount: 1
image:
  repository: "ghcr.io/nexaflowb2b/finance-service"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: "finance-service"
  port: 8003
config:
  map: {}
secret:
  create: true
  sealedData:
    SECRET_KEY: "" # Paste your kubeseal output here
env: []

