namespace: "dev"
secret:
  create: true
  sealedData:
    SECRET_KEY: "AgA6jYWZbXEiCzzUJc6X3fl6uRUIeKrrgEbDUhal/h5J+uFRihgWJDRi+LF6fbTvbdlVqZ65eyzIxn4oS92wBR1o9IlMVoN3Y/6m9jLsQcaSDmAorEXhDqyRhFp8UexeFwwfHAC/ldJMoke7+SFUGDMk6IZGQaOphsPUVdaeC1cX91R4ZkXu5kYEHVFj7IibL3ayTcsUFbGIxGRH85eLITIDJ8nAUquZd6qH1ZoBxTT97/5vK8svqCoci4H4RSOD8x9Kjh9MfVrAbsOCfg96LtCwbPNQ+GozH3DL9kZiySWy98zSndDRv+WWA+97KWM0MpBPeiA3qEWKL3qHLFYjoXgze+n3ykqgsCXA8gDNFFqouB1at2fs9eVkpMb8muum+Vh58LMpvNciYWRzWB7MdY8NTBpR663YDUEm92mPdoGJmhleBpWH4TCZ4NyGH3SCzBn4WLFQMQ0B7lH4JjfzS4L21gyrZnObdUXUCW3fY5bZFiHjLuDkKW5qIKlhIbAmSPd8xIrBi9r9io1vG8artIeJxR8zhKtWdBeghNqEAIX4773kJDNWhSX7tJQnDN8KaGeZqRsjpIjPk0Qj2jNlZFOyyL2zEIPybtjwZH7XA4JeeboKxid5jEqnc9TRRH3jhEKn8PwzO9VF5Ps7g7HqpWGX98l+RP+r7USK6CD59Hn3j+i+vNQ/oCMWBSu/Bw06OG+i+m8J4MqOuKt9wvorm0z0BpTpmzprYW3JWi+1VME7vw=="
    DATABASE_URL: "AgCmxmuZHN33zJuCklDbwUVUOa+MwuDY2xo8wvVi19lsm5yaRIlt4XZVDVC4aHBXyO+pcqTUZeDiTUnHhl7FHgDbxwHdu8VUDKXcfr2hsRkqb58NtGmn1pGRDO9RJf684pqlMxxo1Mh76RCoob2xpwueDF+CQpVtJeHpOq+/5LMRdRbhB/CwjosZjS472vBNQfMThfXF5kDZ7f6SxCRHRxe7WJX7s9ltthimk5S3hLvzPC/4pyttdlle2cLzS13CHbjOchGw1A+6pRM73LT1Jmdb0FrdaxAo08G7SbNxfV2p6Yb1ij679ZWwGpsJ4VyQkDCjV2Y+7MASKaugcdQMDJeOoqOPo/iizLGqKahcii2vp3tuCMZs+CCmOEFUVAOOESIRB4anD48wBBVWk+2tS2Fb4iWdNHeAux+rK8hBRqaCwEPznT35njO1HE26xsViS1GmjynmEq1V5A2YjCdZX/6pzEsaGiju+b5MtKu4WFHvZGA0TN1akw+FQGHzji8590nJQR4KAvWdxHxD9LwxAfR3CBtVQfW7cGy3nIDsLhD44eDXSC007Vyazn3UhNRHhotx6pivwTdw5FIALkptZVRADbiV11PSzpt5akTi3bvSvdkdEZxoCIAZLJ7/MnNu9FTGNm8KvMoxibtQ5ANiPsuvw3opFS16lgqvb2OW0MsYbOXBLxIae42irO5CEFTeT32rvXdMCxeY+vl31h11NDiVLDOn9GrZWSDCbUpV5Vij2YLZG5OZMtxHOhaA/g8DTbDo5e/qKD6tzcyJ30+KfxOMlTg6CA=="
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: inventory-service-secret
        key: DATABASE_URL
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: inventory-service-secret
        key: SECRET_KEY
  - name: ALGORITHM
    value: "HS256"
  - name: ACCESS_TOKEN_EXPIRE_MINUTES
    value: "60"
