namespace: ""
appName: "inventory-service"
replicaCount: 1
image:
  repository: "REGISTRY/nexaflow/inventory-service"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: "inventory-service"
  port: 8002
config:
  map: {}
secret:
  create: false
  stringData: {}
env: []
